image:
  file: Dockerfile
ports:
  - port: 6080
tasks:
  - init: yarn
    command: ./scripts/code.sh
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
